# Generated by Django 5.1.3 on 2024-11-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('elektro_projects', '0003_customer_person_remove_project_assigned_to_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customers.customer'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_persons',
            field=models.ManyToManyField(blank=True, related_name='projects', to='people.person'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
